---
- name: Check if k3s is installed
  shell: k3s -v
  ignore_errors: true
  register: k3s_check

- name: Run k3s installation script on server
  shell: curl -sfL https://get.k3s.io | sh -
  when: k3s_check.rc != 0 and inventory_hostname in groups['rpi_primary']

- name: Register server token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: server_token
  when: k3s_check.rc == 0 and inventory_hostname in groups['rpi_primary']

#- name: debug
#  debug:
#    var: hostvars['rpi-1']['ansible_host']
#  when: inventory_hostname in groups['rpi_primary']

- name: Run k3s installation script on agents
  shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['rpi-1']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['rpi-1']['server_token']['stdout'] }} sh -"
  when: k3s_check.rc != 0 and inventory_hostname in groups['rpi_secondary']