---
- name: Check if Docker is installed
  shell: docker version
  ignore_errors: true
  register: docker_check

- name: Run Docker installation script
  shell: curl -sfL https://get.docker.com | sh -
  when: docker_check.rc != 0

- name: Add existing user 'charles' to group docker
  user:
    name: charles
    groups: docker
    append: yes